### ISSUE TITLE
Add licensing and citation information

### ISSUE THREAD

**Issue by praftery** [CenterForTheBuiltEnvironment/fan-tool#5]
bottom of tool page

**Comment by FedericoTartarini** [comment]
Please use this [link](https://github.com/FedericoTartarini/comfort_tool/blob/master/templates/layout.html) to access the HTML code I wrote for the navigation bar and footnote of the CBE thermal comfort tool. Please feel free to copy and paste in your HTML file. You can access the new comfort tool using this [link](https://shrouded-refuge-24438.herokuapp.com)
